{
 "title": "MOD1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# MOD1" } },
  { "title": "Ubication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Ubication", "type": "geomap", "gridPos": { "h": 10, "w": 21, "x": 0, "y": 3 } },
  {
   "title": " Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "159" }
   ]
  },
  { "title": "Real time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Humity",
   "type": "gauge",
   "description": "Humity",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "description": "Pressure",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pressure" }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Humity",
   "type": "timeseries",
   "description": "Humity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "description": "Pressure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    { "expr": "pressure" }
   ]
  }
 ]
}